export default {
  search: require("../assets/icons/search.png"),
  line: require("../assets/icons/line.png"),
  scan: require("../assets/icons/scan.png"),
  cart: require("../assets/icons/cart.png"),
  mess: require("../assets/icons/messenger.png"),
  camera: require("../assets/icons/camera.png"),
  coin: require("../assets/icons/coin.png"),
  wallet: require("../assets/icons/wallet.png"),
  food: require("../assets/icons/food.png"),
  flash: require("../assets/icons/flash.png"),
  gift: require("../assets/icons/giftbox.png"),
  right_arrow: require("../assets/icons/right-arrow.png"),
  salad: require("../assets/icons/salad.png"),
  location: require("../assets/icons/location.png"),
  card: require("../assets/icons/flight.png"),
};
